apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-daemonset
  labels:
    app: my-daemonset
spec:
  selector:
    matchLabels:
      app: my-daemonset
  template:
    metadata:
      labels:
        app: my-daemonset
    spec:
      containers:
      - name: my-daemonset-container
        image: busybox
        command: ['sh', '-c', 'echo DaemonSet pod running on $(hostname) && sleep 3600; '] 
        