apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: microservices-demo
type: Opaque
data:
  # echo -n "postgres" | base64
  username: cG9zdGdyZXM=
  # echo -n "SuperSecretDBPassword123!" | base64
  password: U3VwZXJTZWNyZXREQlBhc3N3b3JkMTIzIQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: api-keys
  namespace: microservices-demo
type: Opaque
data:
   # echo -n "my-jwt-secret-key-2024" | base64
   jwt-secret: bXktand0LXNlY3JldC1rZXktMjAyNA==
    # echo -n "api-allow-key-xyz789" | base64
   api-key: YXBpLWFsbG93LWtleS14eXo3ODk=