[master]
192.168.122.18 ansible_user=rayen ansible_password=123456 ansible_become_password=123456

[workers]
192.168.122.188 ansible_user=rayen ansible_password=123456 ansible_become_password=123456
192.168.122.236 ansible_user=rayen ansible_password=123456 ansible_become_password=123456
