[master]
192.168.122.207 ansible_user=rayen ansible_password=123456 ansible_become_password=123456

[workers]
192.168.122.220 ansible_user=rayen ansible_password=123456 ansible_become_password=123456
192.168.122.138 ansible_user=rayen ansible_password=123456 ansible_become_password=123456


[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_become=true
ansible_become_method=sudo
ansible_become_ask_pass=false