apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  volumes:
    - name: service-account-secret
      secret:
        secretName: service-account-secret
  containers:
    - name: secret-test-container
      image: registry.k8s.io/busybox
      command:
        - ls
        - "-l"
        - "/etc/secret-volume"
      volumeMounts:
        - name: service-account-secret
          readOnly: true
          mountPath: "/etc/secret-volume"